### PR TITLE
Bump aiocoap to 0.4.5 for 9.x release

### PR DESCRIPTION
**Pull request by MartinHjelmare**
- Bump aiocoap to 0.4.5.
- Loosen the requirement specifier for aiocoap DTLSSocket and allow all higher patch versions.
- Bump version of pytradfri to 9.0.1. We'll release this as a patch release for 9.x to unblock the Home Assistant integration that causes a requirement version mismatch for aiocoap currently. More work is needed until we can use pytradfri 10+ in Home Assistant.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
CI won't run for this PR due to the action settings in this branch. I've run tests locally and tested this in Home Assistant successfully.

**Review by ggravlingen — APPROVED** [review]

**Comment by ggravlingen** [comment]
I don't quite understand how a 9.0.1 will work in Home Assistant but I'm curious to learn the process here.

**Comment by MartinHjelmare** [comment]
We currently run 9.0.0 in Home Assistant. We'll bump pytradfri to 9.0.1 in Home Assistant after we release the patch release here. The only change relevant for the tradfri integration is the aiocoap bump.

**Comment by ggravlingen** [comment]
> We currently run 9.0.0 in Home Assistant. We'll bump pytradfri to 9.0.1 in Home Assistant after we release the patch release here. The only change relevant for the tradfri integration is the aiocoap bump.

It's the patch release thing I've never seen before but I'm eager to learn how it works!

**Comment by MartinHjelmare** [comment]
You can tag a release from any branch, not only the main branch. I've pushed a 9.x branch to upstream in this repo with a HEAD at the tag 9.0.0. This is the target branch of this PR. We'll then tag a new release 9.0.1 from the 9.x branch.

**Comment by ggravlingen** [comment]
> You can tag a release from any branch, not only the main branch. I've pushed a 9.x branch to upstream in this repo with a HEAD at the tag 9.0.0. This is the target branch of this PR. After merging this PR, we'll tag a new release 9.0.1 from the 9.x branch.

Nice, didn't know this. Thanks!

**Comment by MartinHjelmare** [comment]
https://pypi.org/project/pytradfri/9.0.1/

**Pull request merged**
