### PR TITLE
Bumb version to 7.1.0

### PR DESCRIPTION
**Pull request by janiversen**
Add support for air purifier.
Version is needed to add support in HA:
https://github.com/home-assistant/core/issues/57842

### CODE REVIEW

**Comment by janiversen** [comment]
I agree bump the minor version is better.

**Comment by ggravlingen** [comment]
Available on pypi now.

**Comment by MartinHjelmare** [comment]
@ggravlingen there's an untagged tag now, besides the 7.1.0 release. Please make sure that all actions are done before releasing the Github release.

https://github.com/home-assistant-libs/pytradfri/tags

**Comment by ggravlingen** [comment]
All actions were green when I did the release but I do realize something went wrong here. The untagged tag can be deleted, yes?

**Comment by MartinHjelmare** [comment]
Yes, looks like it's just a duplicate tag of the release. 👍

**Pull request merged**
